@baseUrl = http://127.0.0.1:8000/api/v1

### LOGIN
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "1726301821",
  "password": "Darwin1388"
}

### CULTIVOS
GET {{baseUrl}}/guide/crops
Accept: application/json
Authorization: Bearer {{login.response.body.data.token}}

### PROBLEMAS
GET {{baseUrl}}/guide/problems?crop_id=1
Accept: application/json
Authorization: Bearer {{login.response.body.data.token}}

### PROTOCOLO
GET {{baseUrl}}/guide/protocol?crop_id=1&problem_id=1
Accept: application/json
Authorization: Bearer {{login.response.body.data.token}}
