@baseUrl = http://127.0.0.1:8000/api/v1
@token = 17|3CCWACV0uLQJnlTUQuOb4NyxSAk1gje5gSDHJU1Ff8740871
###############################################################
### LOGIN
###############################################################

POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "username": "1726301821",
    "password": "Darwin1388"
}

###############################################################
### CAMPAÑA ACTUAL
###############################################################

GET {{baseUrl}}/cashback/current-campaign
Authorization: Bearer {{token}}
Accept: application/json

###############################################################
### SALDO DEL USUARIO
###############################################################

GET {{baseUrl}}/cashback/balance
Authorization: Bearer {{token}}
Accept: application/json

###############################################################
### HISTORIAL
###############################################################

GET {{baseUrl}}/cashback/history
Authorization: Bearer {{token}}
Accept: application/json

###############################################################
### DETALLE FACTURA
###############################################################

GET {{baseUrl}}/cashback/invoices/1
Authorization: Bearer {{token}}
Accept: application/json

###############################################################
### REGISTRAR FACTURA
###############################################################

POST {{baseUrl}}/cashback/invoices
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "cashback_campaign_id": 1,
    "numero_factura_original": "123456",
    "fecha_factura": "2026-07-30",
    "items": [
        {
            "product_id": 1,
            "valor": 25.50
        },
        {
            "product_id": 2,
            "valor": 10.75
        }
    ]
}
